name: FAST - scalability

on:
  schedule:
    - cron: '0 17 * * 1-5'  # At 13 PM every day - BR time
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      test_suite_size:
        description: 'number of test cases in the test suite. a positive integer, e.g. 1000.'
        default: '1000'
      test_case_size:
        description: 'size of the test cases: small, medium, large'
        default: 'medium'
      algorithm:
        description: 'algorithm used for prioritization: FAST-pw, FAST-one, FAST-log, FAST-sqrt, FAST-all, STR, I-TSD, ART-D, ART-F, GT, GA, GA-S'
        default: 'FAST-one'

jobs:
  job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7]
        
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install dependencies
        run: |
          curl https://bootstrap.pypa.io/pip/2.7/get-pip.py -o get-pip.py
          python2 get-pip.py
          if [ -f requirements.txt ]; then pip2 install -r requirements.txt; fi

      - name: Run FAST - generate scalability
        id: FAST-generate-scalability
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE
          bash actions_scalability_ts.sh ${{ github.event.inputs.test_suite_size }} ${{ github.event.inputs.test_case_size }}

      - name: Generating scalability artifact testset
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: scalability-testset
          path: ${{github.workspace}}/scalability/input/*.txt
          retention-days: 30

      - name: Download scalability artifact
        uses: actions/download-artifact@v2
        with:
          name: scalability-testset

      - name: Run FAST - scalability
          id: scalability
          shell: bash
          run: |
            cd $GITHUB_WORKSPACE
            bash actions_scalability.sh ${{ github.event.inputs.test_suite_size }}
            ${{ github.event.inputs.test_case_size }} ${{ github.event.inputs.algorithm }}

      - name: Register the scalability report
          if: ${{ always() }}
          uses: actions/upload-artifact@v2
          with:
            name: prioritize run report
            path: ${{github.workspace}}/scalability/*
            retention-days: 30